import type { ApiResult } from '@/types/api.types'
import type { Service } from '@/types/service.types'
import type { ServiceCategory } from '@/types/user.types'

const MANUAL_SERVICES: Service[] = [
  // MECHANIC
  {
    id: 101,
    title: 'Engine Repair & Diagnostics',
    description: 'Full engine inspection, fault diagnosis and repair by certified mechanics. Covers all vehicle types.',
    category: 'mechanic',
    basePrice: 3500,
    rating: 4.8,
    thumbnail: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&q=80',
    workersAvailable: 5,
    estimatedDuration: '2–4 hours',
    tags: ['mechanic', 'engine', 'repair', 'car', 'vehicle', 'diagnostics'],
  },
  {
    id: 102,
    title: 'Brake System Service',
    description: 'Complete brake inspection, pad replacement and brake fluid top-up. Safety guaranteed.',
    category: 'mechanic',
    basePrice: 2500,
    rating: 4.7,
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    workersAvailable: 4,
    estimatedDuration: '1–2 hours',
    tags: ['mechanic', 'brake', 'safety', 'car'],
  },
  {
    id: 103,
    title: 'Oil Change & Filter',
    description: 'Quick oil change with premium oil and filter replacement. Keeps your engine running smooth.',
    category: 'mechanic',
    basePrice: 1500,
    rating: 4.9,
    thumbnail: 'https://images.unsplash.com/photo-1632823471565-1ecdf5c6da22?w=400&q=80',
    workersAvailable: 6,
    estimatedDuration: '30–60 mins',
    tags: ['mechanic', 'oil', 'filter', 'maintenance'],
  },
  {
    id: 104,
    title: 'Tyre Replacement & Balancing',
    description: 'Professional tyre fitting, wheel balancing and alignment for all vehicle types.',
    category: 'mechanic',
    basePrice: 2000,
    rating: 4.6,
    thumbnail: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=400&q=80',
    workersAvailable: 3,
    estimatedDuration: '1–2 hours',
    tags: ['mechanic', 'tyre', 'wheel', 'balancing'],
  },

  // AC TECHNICIAN
  {
    id: 201,
    title: 'AC Installation',
    description: 'Professional split AC or window AC installation with piping, bracket fixing and testing.',
    category: 'ac-technician',
    basePrice: 4500,
    rating: 4.8,
    thumbnail: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&q=80',
    workersAvailable: 4,
    estimatedDuration: '2–3 hours',
    tags: ['ac', 'installation', 'split ac', 'cooling'],
  },
  {
    id: 202,
    title: 'AC Deep Cleaning',
    description: 'Full AC unit cleaning including filter wash, coil cleaning and sanitization for better air quality.',
    category: 'ac-technician',
    basePrice: 2500,
    rating: 4.9,
    thumbnail: 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=400&q=80',
    workersAvailable: 6,
    estimatedDuration: '1–2 hours',
    tags: ['ac', 'cleaning', 'filter', 'sanitize'],
  },
  {
    id: 203,
    title: 'Gas Refill & Leak Check',
    description: 'AC refrigerant gas refill with full leak detection test. Restores full cooling performance.',
    category: 'ac-technician',
    basePrice: 3000,
    rating: 4.7,
    thumbnail: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400&q=80',
    workersAvailable: 3,
    estimatedDuration: '1–2 hours',
    tags: ['ac', 'gas refill', 'refrigerant', 'leak'],
  },
  {
    id: 204,
    title: 'AC Repair & Fault Fix',
    description: 'Diagnose and fix AC not cooling, strange noise, water leak or compressor issues.',
    category: 'ac-technician',
    basePrice: 2000,
    rating: 4.6,
    thumbnail: 'https://images.unsplash.com/photo-1562184552-997c461abbe6?w=400&q=80',
    workersAvailable: 5,
    estimatedDuration: '1–3 hours',
    tags: ['ac', 'repair', 'fault', 'not cooling'],
  },

  // PLUMBER
  {
    id: 301,
    title: 'Pipe Leak Repair',
    description: 'Fast detection and repair of water pipe leaks. Prevents wall damage and water wastage.',
    category: 'plumber',
    basePrice: 1500,
    rating: 4.8,
    thumbnail: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=400&q=80',
    workersAvailable: 5,
    estimatedDuration: '1–2 hours',
    tags: ['plumber', 'leak', 'pipe', 'water', 'repair'],
  },
  {
    id: 302,
    title: 'Drain Cleaning & Unblocking',
    description: 'Professional drain unblocking for kitchen, bathroom and outdoor drains using modern tools.',
    category: 'plumber',
    basePrice: 1800,
    rating: 4.7,
    thumbnail: 'https://images.unsplash.com/photo-1585704032915-c3400305e979?w=400&q=80',
    workersAvailable: 4,
    estimatedDuration: '1–2 hours',
    tags: ['plumber', 'drain', 'blocked', 'cleaning'],
  },
  {
    id: 303,
    title: 'Water Heater Installation',
    description: 'Install or replace electric or solar water heaters with full safety checks and testing.',
    category: 'plumber',
    basePrice: 4000,
    rating: 4.8,
    thumbnail: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&q=80',
    workersAvailable: 3,
    estimatedDuration: '2–3 hours',
    tags: ['plumber', 'water heater', 'installation', 'solar'],
  },
  {
    id: 304,
    title: 'Toilet & Tap Repair',
    description: 'Fix running toilets, dripping taps, flush system issues and replace washers or valves.',
    category: 'plumber',
    basePrice: 1200,
    rating: 4.6,
    thumbnail: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=400&q=80',
    workersAvailable: 6,
    estimatedDuration: '1–2 hours',
    tags: ['plumber', 'toilet', 'tap', 'flush', 'drip'],
  },

  // ELECTRICIAN
  {
    id: 401,
    title: 'Home Wiring & Rewiring',
    description: 'Complete home electrical wiring or rewiring with safety compliance. All cable types covered.',
    category: 'electrician',
    basePrice: 8000,
    rating: 4.9,
    thumbnail: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400&q=80',
    workersAvailable: 3,
    estimatedDuration: '4–8 hours',
    tags: ['electrician', 'wiring', 'rewiring', 'electrical', 'home'],
  },
  {
    id: 402,
    title: 'Switchboard Installation & Repair',
    description: 'Install new switchboards or repair faulty ones. MCB, RCD and socket replacements included.',
    category: 'electrician',
    basePrice: 2500,
    rating: 4.8,
    thumbnail: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&q=80',
    workersAvailable: 5,
    estimatedDuration: '1–3 hours',
    tags: ['electrician', 'switchboard', 'MCB', 'socket', 'fuse'],
  },
  {
    id: 403,
    title: 'Ceiling Fan Installation',
    description: 'Safe and neat ceiling fan fitting with wiring, switch installation and balancing.',
    category: 'electrician',
    basePrice: 1500,
    rating: 4.7,
    thumbnail: 'https://images.unsplash.com/photo-1564540586988-aa4e53c3d799?w=400&q=80',
    workersAvailable: 6,
    estimatedDuration: '1–2 hours',
    tags: ['electrician', 'fan', 'ceiling fan', 'installation'],
  },
  {
    id: 404,
    title: 'Solar Panel Setup',
    description: 'Residential solar panel installation with inverter setup and grid connection.',
    category: 'electrician',
    basePrice: 25000,
    rating: 4.9,
    thumbnail: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&q=80',
    workersAvailable: 2,
    estimatedDuration: '1–2 days',
    tags: ['electrician', 'solar', 'panel', 'renewable', 'energy'],
  },

  // CARPENTER
  {
    id: 501,
    title: 'Custom Furniture Making',
    description: 'Handcrafted wardrobes, beds, tables and shelves made to your exact measurements and design.',
    category: 'carpenter',
    basePrice: 15000,
    rating: 4.9,
    thumbnail: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80',
    workersAvailable: 3,
    estimatedDuration: '2–5 days',
    tags: ['carpenter', 'furniture', 'wardrobe', 'custom', 'wood'],
  },
  {
    id: 502,
    title: 'Door Repair & Installation',
    description: 'Fix sagging, squeaking or broken doors. Install new wooden or PVC doors with frames.',
    category: 'carpenter',
    basePrice: 3000,
    rating: 4.7,
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    workersAvailable: 4,
    estimatedDuration: '2–4 hours',
    tags: ['carpenter', 'door', 'repair', 'installation', 'wood'],
  },
  {
    id: 503,
    title: 'Kitchen Cabinet Installation',
    description: 'Design and install modern kitchen cabinets with hinges, handles and drawer systems.',
    category: 'carpenter',
    basePrice: 20000,
    rating: 4.8,
    thumbnail: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80',
    workersAvailable: 2,
    estimatedDuration: '1–3 days',
    tags: ['carpenter', 'kitchen', 'cabinet', 'installation'],
  },
  {
    id: 504,
    title: 'Wooden Flooring',
    description: 'Install or repair wooden or laminate flooring with proper finishing and edge treatment.',
    category: 'carpenter',
    basePrice: 12000,
    rating: 4.6,
    thumbnail: 'https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=400&q=80',
    workersAvailable: 3,
    estimatedDuration: '1–2 days',
    tags: ['carpenter', 'flooring', 'wooden', 'laminate'],
  },

  // CLEANER
  {
    id: 601,
    title: 'Full Home Deep Cleaning',
    description: 'Top to bottom deep clean of your entire home. Kitchen, bathrooms, bedrooms and living areas.',
    category: 'cleaner',
    basePrice: 5000,
    rating: 4.9,
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    workersAvailable: 6,
    estimatedDuration: '4–6 hours',
    tags: ['cleaner', 'deep cleaning', 'home', 'sanitize', 'hygiene'],
  },
  {
    id: 602,
    title: 'Sofa & Upholstery Cleaning',
    description: 'Steam cleaning for sofas, chairs and curtains. Removes stains, dust and allergens.',
    category: 'cleaner',
    basePrice: 3000,
    rating: 4.8,
    thumbnail: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80',
    workersAvailable: 4,
    estimatedDuration: '2–3 hours',
    tags: ['cleaner', 'sofa', 'upholstery', 'steam', 'stain'],
  },
  {
    id: 603,
    title: 'Carpet & Rug Washing',
    description: 'Professional carpet washing with industrial equipment. Dry within 2–3 hours.',
    category: 'cleaner',
    basePrice: 2500,
    rating: 4.7,
    thumbnail: 'https://images.unsplash.com/photo-1527515637462-cff94aca208f?w=400&q=80',
    workersAvailable: 3,
    estimatedDuration: '2–4 hours',
    tags: ['cleaner', 'carpet', 'rug', 'washing'],
  },
  {
    id: 604,
    title: 'Window & Glass Cleaning',
    description: 'Streak-free window cleaning for homes and offices. Interior and exterior included.',
    category: 'cleaner',
    basePrice: 2000,
    rating: 4.6,
    thumbnail: 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=400&q=80',
    workersAvailable: 5,
    estimatedDuration: '1–3 hours',
    tags: ['cleaner', 'window', 'glass', 'streak-free'],
  },

  // PAINTER
  {
    id: 701,
    title: 'Interior Wall Painting',
    description: 'Professional interior painting with premium paints. Walls, ceilings and trims covered.',
    category: 'painter',
    basePrice: 8000,
    rating: 4.8,
    thumbnail: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=400&q=80',
    workersAvailable: 4,
    estimatedDuration: '1–3 days',
    tags: ['painter', 'interior', 'wall', 'paint', 'ceiling'],
  },
  {
    id: 702,
    title: 'Exterior House Painting',
    description: 'Weather-resistant exterior painting that protects and beautifies your home facade.',
    category: 'painter',
    basePrice: 15000,
    rating: 4.7,
    thumbnail: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400&q=80',
    workersAvailable: 3,
    estimatedDuration: '2–5 days',
    tags: ['painter', 'exterior', 'house', 'weather', 'facade'],
  },
  {
    id: 703,
    title: 'Waterproofing Service',
    description: 'Bathroom, roof and basement waterproofing to prevent leaks and dampness permanently.',
    category: 'painter',
    basePrice: 6000,
    rating: 4.9,
    thumbnail: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&q=80',
    workersAvailable: 3,
    estimatedDuration: '1–2 days',
    tags: ['painter', 'waterproof', 'roof', 'bathroom', 'damp'],
  },
  {
    id: 704,
    title: 'Texture & Decorative Paint',
    description: 'Modern texture finishes, stucco, stone effect and designer wall art for stylish interiors.',
    category: 'painter',
    basePrice: 10000,
    rating: 4.8,
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    workersAvailable: 2,
    estimatedDuration: '2–4 days',
    tags: ['painter', 'texture', 'decorative', 'design', 'stucco'],
  },

  // GENERAL
  {
    id: 801,
    title: 'General Handyman Service',
    description: 'All-round handyman for small repairs, fixing, assembling and general home maintenance tasks.',
    category: 'general',
    basePrice: 1500,
    rating: 4.7,
    thumbnail: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&q=80',
    workersAvailable: 8,
    estimatedDuration: '1–3 hours',
    tags: ['handyman', 'general', 'repair', 'maintenance', 'fix'],
  },
  {
    id: 802,
    title: 'Furniture Assembly',
    description: 'Fast and neat assembly of IKEA and flat-pack furniture. All tools provided.',
    category: 'general',
    basePrice: 1200,
    rating: 4.8,
    thumbnail: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80',
    workersAvailable: 5,
    estimatedDuration: '1–3 hours',
    tags: ['general', 'furniture', 'assembly', 'IKEA', 'flatpack'],
  },
  {
    id: 803,
    title: 'Moving & Relocation Help',
    description: 'Professional help with packing, moving furniture and setting up your new home.',
    category: 'general',
    basePrice: 5000,
    rating: 4.6,
    thumbnail: 'https://images.unsplash.com/photo-1600518464441-9154a4dea21b?w=400&q=80',
    workersAvailable: 4,
    estimatedDuration: '3–6 hours',
    tags: ['general', 'moving', 'relocation', 'packing', 'shifting'],
  },
  {
    id: 804,
    title: 'Garden & Lawn Maintenance',
    description: 'Lawn mowing, hedge trimming, plant care and garden cleanup to keep your garden beautiful.',
    category: 'general',
    basePrice: 2000,
    rating: 4.7,
    thumbnail: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    workersAvailable: 4,
    estimatedDuration: '2–4 hours',
    tags: ['general', 'garden', 'lawn', 'mowing', 'plants', 'outdoor'],
  },
]

export const productService = {
  async fetchServices(): Promise<ApiResult<Service[]>> {
    return { success: true, data: MANUAL_SERVICES }
  },
}